<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sania Bala">
<meta name="dcterms.date" content="2026-05-24">

<title>Democratic Backsliding and Foreign Aid</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="data_merge_files/libs/clipboard/clipboard.min.js"></script>
<script src="data_merge_files/libs/quarto-html/quarto.js"></script>
<script src="data_merge_files/libs/quarto-html/popper.min.js"></script>
<script src="data_merge_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="data_merge_files/libs/quarto-html/anchor.min.js"></script>
<link href="data_merge_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="data_merge_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="data_merge_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="data_merge_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="data_merge_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Democratic Backsliding and Foreign Aid</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sania Bala </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 24, 2026</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<p>Loading required packages. Any missing packages are installed automatically.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>required_packages <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"tidyverse"</span>, <span class="st">"WDI"</span>, <span class="st">"countrycode"</span>, <span class="st">"MASS"</span>, <span class="st">"here"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>missing_packages <span class="ot">&lt;-</span> required_packages[<span class="sc">!</span>required_packages <span class="sc">%in%</span> <span class="fu">installed.packages</span>()[, <span class="st">"Package"</span>]]</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">length</span>(missing_packages) <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="fu">install.packages</span>(missing_packages, <span class="at">repos =</span> <span class="st">"https://cloud.r-project.org"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(WDI)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(countrycode)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># MASS is loaded later, just before the models, to avoid it masking dplyr::select</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<section id="load-raw-data" class="level3">
<h3 class="anchored" data-anchor-id="load-raw-data">Load raw data</h3>
<p>We use two datasets:</p>
<ul>
<li><strong>V-Dem</strong> (Varieties of Democracy): country-year measures of democracy, governance, and civil liberties</li>
<li><strong>OECD DAC2A</strong>: bilateral ODA (Official Development Assistance) disbursements by donor and recipient country, 2010–2020</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>vdem <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"VDEM.csv"</span>))</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>oecd_raw <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"OECD DAC2A.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="clean-and-aggregate-oecd-data" class="level3">
<h3 class="anchored" data-anchor-id="clean-and-aggregate-oecd-data">Clean and aggregate OECD data</h3>
<p>Country names differ between the two datasets, so we standardize OECD recipient names to match V-Dem before merging. We then aggregate from donor-level rows to total ODA received per recipient country per year.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>oecd_clean <span class="ot">&lt;-</span> oecd_raw <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Recipient =</span> <span class="fu">recode</span>(Recipient,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Myanmar"</span>                                           <span class="ot">=</span> <span class="st">"Burma/Myanmar"</span>,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Cabo Verde"</span>                                        <span class="ot">=</span> <span class="st">"Cape Verde"</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"China (People's Republic of)"</span>                      <span class="ot">=</span> <span class="st">"China"</span>,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Côte d'Ivoire"</span>                                     <span class="ot">=</span> <span class="st">"Ivory Coast"</span>,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Lao People's Democratic Republic"</span>                  <span class="ot">=</span> <span class="st">"Laos"</span>,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Democratic People's Republic of Korea"</span>             <span class="ot">=</span> <span class="st">"North Korea"</span>,</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Palestinian Authority or West Bank and Gaza Strip"</span> <span class="ot">=</span> <span class="st">"Palestine/West Bank"</span>,</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Congo"</span>                                             <span class="ot">=</span> <span class="st">"Republic of the Congo"</span>,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Syrian Arab Republic"</span>                              <span class="ot">=</span> <span class="st">"Syria"</span>,</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Gambia"</span>                                            <span class="ot">=</span> <span class="st">"The Gambia"</span>,</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Viet Nam"</span>                                          <span class="ot">=</span> <span class="st">"Vietnam"</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>oecd <span class="ot">&lt;-</span> oecd_clean <span class="sc">%&gt;%</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Recipient, TIME_PERIOD) <span class="sc">%&gt;%</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_oda_usd_millions =</span> <span class="fu">sum</span>(OBS_VALUE, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">country_name =</span> Recipient, <span class="at">year =</span> TIME_PERIOD)</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(oecd, <span class="fu">here</span>(<span class="st">"sania/oecd_clean.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="merge-v-dem-and-oecd" class="level3">
<h3 class="anchored" data-anchor-id="merge-v-dem-and-oecd">Merge V-Dem and OECD</h3>
<p>We merge on <code>country_name</code> and <code>year</code>, keeping all V-Dem observations (left join). We also compute <code>delta_polyarchy</code> — the year-over-year change in the electoral democracy index — <strong>before</strong> subsetting to 2010–2020, so that 2010 observations can draw their lag from 2009.</p>
<ul>
<li>Negative <code>delta_polyarchy</code> = democratic backsliding</li>
<li>Positive <code>delta_polyarchy</code> = democratization</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>merged <span class="ot">&lt;-</span> vdem <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(oecd, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"country_name"</span>, <span class="st">"year"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(country_name, year) <span class="sc">%&gt;%</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(country_name) <span class="sc">%&gt;%</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">delta_polyarchy =</span> v2x_polyarchy <span class="sc">-</span> <span class="fu">lag</span>(v2x_polyarchy)) <span class="sc">%&gt;%</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="subset-to-analysis-variables-20102020" class="level3">
<h3 class="anchored" data-anchor-id="subset-to-analysis-variables-20102020">Subset to analysis variables (2010–2020)</h3>
<p>We keep only the variables needed for analysis and filter to the period covered by the OECD data.</p>
<table class="table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>v2x_polyarchy</code></td>
<td>Electoral democracy level (control)</td>
</tr>
<tr class="even">
<td><code>delta_polyarchy</code></td>
<td>Year-over-year change in democracy (key predictor)</td>
</tr>
<tr class="odd">
<td><code>v2x_corr</code></td>
<td>Political corruption index</td>
</tr>
<tr class="even">
<td><code>v2x_rule</code></td>
<td>Rule of law index</td>
</tr>
<tr class="odd">
<td><code>v2xcl_rol</code></td>
<td>Civil liberties / equality before the law</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>analysis <span class="ot">&lt;-</span> merged <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">&gt;=</span> <span class="dv">2010</span>, year <span class="sc">&lt;=</span> <span class="dv">2020</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    country_name, year, total_oda_usd_millions,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    v2x_polyarchy, delta_polyarchy,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    v2x_corr, v2x_rule, v2xcl_rol</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="add-gdp-per-capita-and-population" class="level3">
<h3 class="anchored" data-anchor-id="add-gdp-per-capita-and-population">Add GDP per capita and population</h3>
<p>GDP per capita and population are not in our V-Dem extract, so we pull them from the World Bank via the <code>WDI</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>wdi <span class="ot">&lt;-</span> <span class="fu">WDI</span>(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">indicator =</span> <span class="fu">c</span>(<span class="at">gdp_per_capita =</span> <span class="st">"NY.GDP.PCAP.KD"</span>,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">population     =</span> <span class="st">"SP.POP.TOTL"</span>),</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">start =</span> <span class="dv">2010</span>, <span class="at">end =</span> <span class="dv">2020</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">extra =</span> <span class="cn">FALSE</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">country_name =</span> <span class="fu">countrycode</span>(iso2c, <span class="at">origin =</span> <span class="st">"iso2c"</span>,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">destination =</span> <span class="st">"country.name"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(country_name)) <span class="sc">%&gt;%</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(country_name, year, gdp_per_capita, population)</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>analysis <span class="ot">&lt;-</span> analysis <span class="sc">%&gt;%</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(wdi, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"country_name"</span>, <span class="st">"year"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="prepare-outcome-variable" class="level3">
<h3 class="anchored" data-anchor-id="prepare-outcome-variable">Prepare outcome variable</h3>
<p>ODA is reported in USD millions (continuous). We convert it to an integer count by rounding to the nearest million and flooring any negative values (loan repayments) to zero, as required by count models.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>analysis <span class="ot">&lt;-</span> analysis <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">oda_count =</span> <span class="fu">pmax</span>(<span class="dv">0</span>, <span class="fu">round</span>(total_oda_usd_millions))) <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>total_oda_usd_millions) <span class="sc">%&gt;%</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(oda_count), <span class="sc">!</span><span class="fu">is.na</span>(v2x_polyarchy))</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(analysis, <span class="fu">here</span>(<span class="st">"sania/analysis_merged.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="models" class="level2">
<h2 class="anchored" data-anchor-id="models">Models</h2>
<section id="model-strategy" class="level3">
<h3 class="anchored" data-anchor-id="model-strategy">Model strategy</h3>
<p>We run two negative binomial models, presented as Model 1 and Model 2:</p>
<ul>
<li><strong>Model 1</strong> tests whether democracy <em>levels</em> predict aid — a baseline consistent with the existing literature</li>
<li><strong>Model 2</strong> adds <code>delta_polyarchy</code> to test whether democratic <em>backsliding</em> predicts aid — the core hypothesis of this paper</li>
</ul>
<p>Keeping both allows us to show that donors respond to where a country sits on the democracy scale, but not necessarily to how fast it is moving. That contrast is itself a substantive finding.</p>
<p>We use negative binomial regression (rather than Poisson) because ODA is heavily overdispersed — its variance far exceeds its mean. Population is included as an offset (<code>log(population)</code>) so that the outcome scales with country size.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="poisson-model-baseline-rejected-due-to-overdispersion" class="level3">
<h3 class="anchored" data-anchor-id="poisson-model-baseline-rejected-due-to-overdispersion">Poisson model (baseline, rejected due to overdispersion)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>poisson_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  oda_count <span class="sc">~</span> v2x_polyarchy <span class="sc">+</span> v2x_corr <span class="sc">+</span> v2x_rule <span class="sc">+</span> v2xcl_rol <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>              <span class="fu">log</span>(gdp_per_capita) <span class="sc">+</span> <span class="fu">offset</span>(<span class="fu">log</span>(population)),</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data   =</span> analysis,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">poisson</span>(<span class="at">link =</span> <span class="st">"log"</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(poisson_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = oda_count ~ v2x_polyarchy + v2x_corr + v2x_rule + 
    v2xcl_rol + log(gdp_per_capita) + offset(log(population)), 
    family = poisson(link = "log"), data = analysis)

Coefficients:
                      Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)         -1.8422898  0.0028197  -653.4   &lt;2e-16 ***
v2x_polyarchy       -1.9022040  0.0022872  -831.7   &lt;2e-16 ***
v2x_corr            -1.4590109  0.0024620  -592.6   &lt;2e-16 ***
v2x_rule            -2.4319931  0.0029246  -831.6   &lt;2e-16 ***
v2xcl_rol            1.7020097  0.0019941   853.5   &lt;2e-16 ***
log(gdp_per_capita) -0.4972946  0.0002594 -1916.8   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 46672421  on 1216  degrees of freedom
Residual deviance: 36501834  on 1211  degrees of freedom
  (119 observations deleted due to missingness)
AIC: 36515302

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
<p>The Poisson model shows all coefficients as highly significant (z-values 600–1900), which is a red flag rather than a good sign. The residual deviance (36,501,834 on 1,211 df) far exceeds what Poisson assumes (deviance ≈ df), confirming severe overdispersion. We switch to negative binomial.</p>
</section>
<section id="model-1-democracy-levels-and-aid-negative-binomial" class="level3">
<h3 class="anchored" data-anchor-id="model-1-democracy-levels-and-aid-negative-binomial">Model 1: Democracy levels and aid (Negative Binomial)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>nb_model <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  oda_count <span class="sc">~</span> v2x_polyarchy <span class="sc">+</span> v2x_corr <span class="sc">+</span> v2x_rule <span class="sc">+</span> v2xcl_rol <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>              <span class="fu">log</span>(gdp_per_capita) <span class="sc">+</span> <span class="fu">offset</span>(<span class="fu">log</span>(population)),</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> analysis</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nb_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm.nb(formula = oda_count ~ v2x_polyarchy + v2x_corr + v2x_rule + 
    v2xcl_rol + log(gdp_per_capita) + offset(log(population)), 
    data = analysis, init.theta = 0.9165152474, link = log)

Coefficients:
                    Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)         -4.13458    0.40927 -10.102  &lt; 2e-16 ***
v2x_polyarchy       -0.99085    0.28752  -3.446 0.000568 ***
v2x_corr            -0.19906    0.30788  -0.647 0.517928    
v2x_rule             1.40996    0.41506   3.397 0.000681 ***
v2xcl_rol            0.55971    0.25862   2.164 0.030448 *  
log(gdp_per_capita) -0.32172    0.03355  -9.589  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Negative Binomial(0.9165) family taken to be 1)

    Null deviance: 1575.1  on 1216  degrees of freedom
Residual deviance: 1425.1  on 1211  degrees of freedom
  (119 observations deleted due to missingness)
AIC: 26448

Number of Fisher Scoring iterations: 1

              Theta:  0.9165 
          Std. Err.:  0.0327 

 2 x log-likelihood:  -26434.0390 </code></pre>
</div>
</div>
<p><strong>Results:</strong> n = 1,217 country-years. Theta = 0.917, confirming overdispersion. Residual deviance = 1,425 on 1,211 df — a much better fit. AIC = 26,448.</p>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Predictor</th>
<th>Estimate</th>
<th>p-value</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>v2x_polyarchy</code></td>
<td>−0.991</td>
<td>&lt;.001</td>
<td>More democratic countries receive less ODA; aid goes to higher-need, less democratic recipients</td>
</tr>
<tr class="even">
<td><code>v2x_corr</code></td>
<td>−0.199</td>
<td>.518</td>
<td>Corruption not significant once other governance variables are controlled</td>
</tr>
<tr class="odd">
<td><code>v2x_rule</code></td>
<td>1.410</td>
<td>&lt;.001</td>
<td>Better rule of law associated with more ODA; donors reward governance quality</td>
</tr>
<tr class="even">
<td><code>v2xcl_rol</code></td>
<td>0.560</td>
<td>.030</td>
<td>Stronger civil liberties associated with more ODA</td>
</tr>
<tr class="odd">
<td><code>log(gdp_per_capita)</code></td>
<td>−0.322</td>
<td>&lt;.001</td>
<td>Richer countries receive less ODA; consistent with need-based allocation</td>
</tr>
</tbody>
</table>
</section>
<section id="model-2-democratic-backsliding-and-aid-negative-binomial" class="level3">
<h3 class="anchored" data-anchor-id="model-2-democratic-backsliding-and-aid-negative-binomial">Model 2: Democratic backsliding and aid (Negative Binomial)</h3>
<p>The key predictor is <code>delta_polyarchy</code> (year-over-year change in <code>v2x_polyarchy</code>). We keep <code>v2x_polyarchy</code> as a level control so that <code>delta_polyarchy</code> captures the effect of change net of overall democratic standing. The expected sign on <code>delta_polyarchy</code> is positive — backsliding (negative delta) should predict less ODA.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>nb_backsliding <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  oda_count <span class="sc">~</span> delta_polyarchy <span class="sc">+</span> v2x_polyarchy <span class="sc">+</span> v2x_corr <span class="sc">+</span> v2x_rule <span class="sc">+</span> v2xcl_rol <span class="sc">+</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>              <span class="fu">log</span>(gdp_per_capita) <span class="sc">+</span> <span class="fu">offset</span>(<span class="fu">log</span>(population)),</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> analysis</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nb_backsliding)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm.nb(formula = oda_count ~ delta_polyarchy + v2x_polyarchy + 
    v2x_corr + v2x_rule + v2xcl_rol + log(gdp_per_capita) + offset(log(population)), 
    data = analysis, init.theta = 0.9160440198, link = log)

Coefficients:
                    Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)         -4.13857    0.40955 -10.105  &lt; 2e-16 ***
delta_polyarchy      0.46633    0.75494   0.618 0.536768    
v2x_polyarchy       -1.00097    0.28856  -3.469 0.000523 ***
v2x_corr            -0.19736    0.30820  -0.640 0.521936    
v2x_rule             1.40205    0.41524   3.377 0.000734 ***
v2xcl_rol            0.56728    0.25891   2.191 0.028446 *  
log(gdp_per_capita) -0.32089    0.03357  -9.559  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Negative Binomial(0.916) family taken to be 1)

    Null deviance: 1574  on 1215  degrees of freedom
Residual deviance: 1424  on 1209  degrees of freedom
  (120 observations deleted due to missingness)
AIC: 26429

Number of Fisher Scoring iterations: 1

              Theta:  0.9160 
          Std. Err.:  0.0327 

 2 x log-likelihood:  -26413.0680 </code></pre>
</div>
</div>
<p><strong>Results:</strong> n = 1,216 country-years. AIC = 26,429 (marginally better than Model 1).</p>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Predictor</th>
<th>Estimate</th>
<th>p-value</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>delta_polyarchy</code></td>
<td>0.466</td>
<td>.537</td>
<td><strong>Not significant.</strong> Direction is correct but effect is indistinguishable from zero</td>
</tr>
<tr class="even">
<td><code>v2x_polyarchy</code></td>
<td>−1.001</td>
<td>&lt;.001</td>
<td>Democracy level remains strongly significant</td>
</tr>
<tr class="odd">
<td>All controls</td>
<td>—</td>
<td>—</td>
<td>Consistent with Model 1</td>
</tr>
</tbody>
</table>
<p><strong>Interpretation:</strong> The backsliding hypothesis is not supported in this specification. Aid allocations respond to a country’s overall democratic standing, but not to year-to-year democratic change. This likely reflects donor inertia — aid budgets are planned in advance and respond slowly to political shifts. Adding fixed effects or a longer lag structure (2–3 years) may surface a delayed donor response.</p>
</section>
</section>
<section id="robustness-checks" class="level2">
<h2 class="anchored" data-anchor-id="robustness-checks">Robustness Checks</h2>
<section id="check-1-alternative-democracy-measures" class="level3">
<h3 class="anchored" data-anchor-id="check-1-alternative-democracy-measures">Check 1: Alternative democracy measures</h3>
<p><code>v2x_polyarchy</code> measures electoral democracy specifically. If the null result is real, it should hold across different conceptualizations of democracy. We test two alternatives:</p>
<ul>
<li><code>v2x_libdem</code> — liberal democracy (adds judicial constraints and civil liberties)</li>
<li><code>v2x_partipdem</code> — participatory democracy (emphasizes civil society and direct participation)</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>analysis_robust <span class="ot">&lt;-</span> merged <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(country_name, year) <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(country_name) <span class="sc">%&gt;%</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">delta_libdem    =</span> v2x_libdem <span class="sc">-</span> <span class="fu">lag</span>(v2x_libdem),</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">delta_partipdem =</span> v2x_partipdem <span class="sc">-</span> <span class="fu">lag</span>(v2x_partipdem)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">&gt;=</span> <span class="dv">2010</span>, year <span class="sc">&lt;=</span> <span class="dv">2020</span>) <span class="sc">%&gt;%</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(country_name, year, v2x_libdem, v2x_partipdem,</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>                delta_libdem, delta_partipdem) <span class="sc">%&gt;%</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(analysis, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"country_name"</span>, <span class="st">"year"</span>))</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>nb_libdem <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>  oda_count <span class="sc">~</span> delta_libdem <span class="sc">+</span> v2x_libdem <span class="sc">+</span> v2x_corr <span class="sc">+</span> v2x_rule <span class="sc">+</span> v2xcl_rol <span class="sc">+</span></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>              <span class="fu">log</span>(gdp_per_capita) <span class="sc">+</span> <span class="fu">offset</span>(<span class="fu">log</span>(population)),</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> analysis_robust</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>nb_partipdem <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>  oda_count <span class="sc">~</span> delta_partipdem <span class="sc">+</span> v2x_partipdem <span class="sc">+</span> v2x_corr <span class="sc">+</span> v2x_rule <span class="sc">+</span> v2xcl_rol <span class="sc">+</span></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>              <span class="fu">log</span>(gdp_per_capita) <span class="sc">+</span> <span class="fu">offset</span>(<span class="fu">log</span>(population)),</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> analysis_robust</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nb_libdem)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm.nb(formula = oda_count ~ delta_libdem + v2x_libdem + v2x_corr + 
    v2x_rule + v2xcl_rol + log(gdp_per_capita) + offset(log(population)), 
    data = analysis_robust, init.theta = 0.9161646518, link = log)

Coefficients:
                    Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)         -4.36839    0.43180 -10.117  &lt; 2e-16 ***
delta_libdem         0.18519    0.91520   0.202 0.839643    
v2x_libdem          -1.29014    0.36556  -3.529 0.000417 ***
v2x_corr            -0.05372    0.31811  -0.169 0.865906    
v2x_rule             1.88982    0.48242   3.917 8.95e-05 ***
v2xcl_rol            0.43191    0.24848   1.738 0.082179 .  
log(gdp_per_capita) -0.32453    0.03372  -9.624  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Negative Binomial(0.9162) family taken to be 1)

    Null deviance: 1574.2  on 1215  degrees of freedom
Residual deviance: 1424.0  on 1209  degrees of freedom
  (752 observations deleted due to missingness)
AIC: 26429

Number of Fisher Scoring iterations: 1

              Theta:  0.9162 
          Std. Err.:  0.0327 

 2 x log-likelihood:  -26412.8530 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nb_partipdem)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm.nb(formula = oda_count ~ delta_partipdem + v2x_partipdem + 
    v2x_corr + v2x_rule + v2xcl_rol + log(gdp_per_capita) + offset(log(population)), 
    data = analysis_robust, init.theta = 0.9340177647, link = log)

Coefficients:
                    Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)         -4.33205    0.41034 -10.557  &lt; 2e-16 ***
delta_partipdem      1.32645    1.19228   1.113 0.265906    
v2x_partipdem       -2.61582    0.36804  -7.107 1.18e-12 ***
v2x_corr            -0.04335    0.30383  -0.143 0.886553    
v2x_rule             1.75979    0.41310   4.260 2.04e-05 ***
v2xcl_rol            0.84263    0.25040   3.365 0.000765 ***
log(gdp_per_capita) -0.31717    0.03329  -9.529  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Negative Binomial(0.934) family taken to be 1)

    Null deviance: 1604.6  on 1215  degrees of freedom
Residual deviance: 1420.9  on 1209  degrees of freedom
  (752 observations deleted due to missingness)
AIC: 26399

Number of Fisher Scoring iterations: 1

              Theta:  0.9340 
          Std. Err.:  0.0334 

 2 x log-likelihood:  -26382.6390 </code></pre>
</div>
</div>
<p><strong>Results:</strong> The null result holds across both alternatives.</p>
<table class="table">
<thead>
<tr class="header">
<th>Model</th>
<th>Delta estimate</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Electoral democracy (<code>delta_polyarchy</code>)</td>
<td>0.466</td>
<td>.537</td>
</tr>
<tr class="even">
<td>Liberal democracy (<code>delta_libdem</code>)</td>
<td>0.185</td>
<td>.840</td>
</tr>
<tr class="odd">
<td>Participatory democracy (<code>delta_partipdem</code>)</td>
<td>1.326</td>
<td>.266</td>
</tr>
</tbody>
</table>
<p>The null result on backsliding is robust across all three conceptualizations of democracy. This consistently points to donor inertia — aid allocations respond to where a country sits on the democracy scale, not to how fast it is moving.</p>
</section>
<section id="check-2-extended-time-window" class="level3">
<h3 class="anchored" data-anchor-id="check-2-extended-time-window">Check 2: Extended time window</h3>
<p>A longer panel would provide more backsliding episodes and more statistical power. However, the OECD DAC2A data in this project only covers 2010–2020. This check should be revisited if the full OECD time series (available from stats.oecd.org back to the 1960s) is downloaded.</p>
</section>
</section>
<section id="potential-improvements" class="level2">
<h2 class="anchored" data-anchor-id="potential-improvements">Potential Improvements</h2>
<ol type="1">
<li><p><strong>Lag the predictors</strong> — currently democracy scores and ODA are measured in the same year, raising reverse causality concerns. Lagging <code>v2x_polyarchy</code> and all controls by one year (t-1) would make the causal direction cleaner.</p></li>
<li><p><strong>Country + year fixed effects</strong> — country fixed effects absorb all time-invariant country characteristics (colonial history, geographic proximity to donors). Year fixed effects absorb global shocks. Can be implemented with the <code>fixest</code> package.</p></li>
<li><p><strong>Check for zero inflation</strong> — if many country-years have zero ODA, a zero-inflated negative binomial (ZINB) may fit better. Check with <code>table(analysis$oda_count == 0)</code>.</p></li>
</ol>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>